// Generated by CoffeeScript 1.6.3
(function() {
  this.app.controller("RollerCtrl", function($scope, $filter, Dice) {
    var ensureInList, ensureNumerical;
    $scope.dice = Dice;
    $scope.rolls = [];
    ensureNumerical = $filter("ensureNumerical");
    ensureInList = $filter("ensureInList");
    $scope.rollDice = function(sides, amount) {
      var doubleFilteredSides, filteredAmount, filteredSides, new_roll, rolled_dice;
      filteredSides = ensureNumerical(sides);
      doubleFilteredSides = ensureInList(filteredSides);
      filteredAmount = ensureNumerical(amount);
      rolled_dice = randy.multiBetween(doubleFilteredSides, filteredAmount);
      new_roll = new dieRoll(rolled_dice, doubleFilteredSides);
      return $scope.rolls.push(new_roll);
    };
    return $scope.clearRolls = function() {
      return $scope.rolls = [];
    };
  });

}).call(this);
