// Generated by CoffeeScript 1.6.3
(function() {
  this.dieRoll = function(rolled_dice, sides) {
    this.dice = rolled_dice.join(", ");
    this.total = rolled_dice.sum();
    this.sides = sides;
    this.amount = rolled_dice.length;
    return this.time = getCurrentDateTime();
  };

}).call(this);
