// Generated by CoffeeScript 1.6.3
(function() {
  this.app.directive("amountfield", function() {
    var errorMessage;
    errorMessage = angular.element("<div class=\"error hide\">Amount must be a number</div>");
    this.link = function(scope) {
      return scope.$watch("amount_of_dice", function(value) {
        var stringified;
        stringified = String(value);
        if (stringified.match(/^\d+$/) || stringified === "undefined" || stringified === "") {
          return errorMessage.addClass("hide");
        } else {
          return errorMessage.removeClass("hide");
        }
      });
    };
    return {
      restrict: "E",
      replace: true,
      template: "<span class=\"amount\"><input autofocus id=\"amount\" type=\"text\" class=\"input-small\" ng-model=\"amount_of_dice\" placeholder=\"Amount\" /></span>",
      compile: function(tElem) {
        tElem.append(errorMessage);
        return link;
      }
    };
  });

}).call(this);
