// Generated by CoffeeScript 1.6.3
(function() {
  this.Array.prototype.sum = function() {
    var a, i;
    a = this[0];
    i = 1;
    while (i < this.length) {
      a = a + this[i];
      i++;
    }
    return a;
  };

  if (!this.Array.prototype.indexOf) {
    this.Array.prototype.indexOf = function(needle) {
      var i;
      i = 0;
      while (i < this.length) {
        if (this[i] === needle) {
          return i;
        }
        i++;
      }
      return -1;
    };
  }

}).call(this);
