// Generated by CoffeeScript 1.6.3
(function() {
  this.app.filter("ensureNumerical", function() {
    return function(text) {
      var stringified;
      stringified = String(text);
      if (stringified.match(/^\d+$/)) {
        return text;
      } else {
        return 0;
      }
    };
  });

  this.app.filter("ensureInList", function(Dice) {
    return function(text) {
      var i, list, mapped;
      list = Dice.types;
      mapped = [];
      i = 0;
      while (i < list.length) {
        mapped.push(list[i].sides);
        i++;
      }
      if (mapped.indexOf(text) > -1) {
        return text;
      } else {
        return mapped[0];
      }
    };
  });

}).call(this);
