// Generated by CoffeeScript 1.6.3
(function() {
  this.getCurrentDateTime = function() {
    var currentTime, day, hours, minutes, month, period, seconds, year;
    currentTime = new Date();
    month = currentTime.getMonth() + 1;
    day = currentTime.getDate();
    year = currentTime.getFullYear();
    hours = currentTime.getHours();
    minutes = currentTime.getMinutes();
    seconds = currentTime.getSeconds();
    period = void 0;
    if (hours > 11) {
      period = "PM";
    } else {
      period = "AM";
    }
    if (hours > 12) {
      hours = hours - 12;
    }
    if (minutes < 10) {
      minutes = "0" + minutes;
    }
    if (seconds < 10) {
      seconds = "0" + seconds;
    }
    return hours + ":" + minutes + ":" + seconds + " " + period + ", " + month + "/" + day + "/" + year;
  };

}).call(this);
