// Generated by CoffeeScript 1.6.3
(function() {
  this.Randy = function() {};

  this.Randy.prototype.between = function(ceil) {
    return Math.floor((Math.random() * ceil) + 1);
  };

  this.Randy.prototype.multiBetween = function(ceil, amount) {
    var i, nums;
    nums = [];
    i = 0;
    while (i < amount) {
      nums.push(this.between(ceil));
      i++;
    }
    return nums;
  };

}).call(this);
